project_id = "cowiviqhrnmhttugozbz"

[functions.insert-call-signal]
verify_jwt = true

[functions.nigeria-locations]
verify_jwt = false

[functions.get-google-maps-token]
verify_jwt = false

[functions.get-google-calendar-config]
verify_jwt = true

[functions.get-turn-credentials]
verify_jwt = true

[functions.emergency-contact-invitation]
verify_jwt = false

[functions.update-panic-alert-status]
verify_jwt = true

[functions.create-ad-campaign-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-support-email-response]
verify_jwt = true

[functions.automation-processor]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = false

[functions.generate-feed-recommendations]
verify_jwt = true

[functions.send-api-request-notification]
verify_jwt = false

[functions.generate-enterprise-api-key]
verify_jwt = true

[functions.generate-cloudinary-signature]
verify_jwt = true

[functions.delete-cloudinary-image]
verify_jwt = true

[functions.send-call-notification]
verify_jwt = false

[functions.log-call-event]
verify_jwt = false

[functions.clean-expired-calls]
verify_jwt = false

[functions.export-user-data]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.logout-user]
verify_jwt = true

[functions.ad-payment-webhook]
verify_jwt = false

[functions.admin-resend-verification]
verify_jwt = true

[functions.alert-processor]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.emergency-alert]
verify_jwt = false

[functions.get-deleted-users]
verify_jwt = true

[functions.nigeria-reverse-geocode]
verify_jwt = false

[functions.notification-delivery]
verify_jwt = false

[functions.process-escalations]
verify_jwt = false

[functions.process-webhook]
verify_jwt = false

[functions.restore-user]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.test-mapbox-api]
verify_jwt = true

[functions.test-stripe-api]
verify_jwt = true
