project_id = "cowiviqhrnmhttugozbz"

[functions.nigeria-locations]
verify_jwt = false

[functions.get-google-maps-token]
verify_jwt = false

[functions.get-google-calendar-config]
verify_jwt = true

[functions.get-turn-credentials]
verify_jwt = true

[functions.emergency-contact-invitation]
verify_jwt = false

[functions.update-panic-alert-status]
verify_jwt = true

[functions.create-ad-campaign-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-support-email-response]
verify_jwt = true

[functions.automation-processor]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = false

[functions.generate-feed-recommendations]
verify_jwt = true

[functions.send-api-request-notification]
verify_jwt = false

[functions.generate-enterprise-api-key]
verify_jwt = true

[functions.generate-cloudinary-signature]
verify_jwt = true

[functions.delete-cloudinary-image]
verify_jwt = true

[functions.send-call-notification]
verify_jwt = false