project_id = "cowiviqhrnmhttugozbz"

[functions.nigeria-locations]
verify_jwt = false

[functions.get-google-maps-token]
verify_jwt = false

[functions.emergency-contact-invitation]
verify_jwt = false