project_id = "cowiviqhrnmhttugozbz"

[functions.nigeria-locations]
verify_jwt = false

[functions.get-google-maps-token]
verify_jwt = false

[functions.get-google-calendar-config]
verify_jwt = true

[functions.emergency-contact-invitation]
verify_jwt = false

[functions.update-panic-alert-status]
verify_jwt = true

[functions.create-ad-payment]
verify_jwt = true

[functions.create-business-promotion-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-support-email-response]
verify_jwt = true